//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServiceDiagnostic {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Diagnostic", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Diagnostic : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDiagnosticField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MedicalConditionField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RegisterDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDiagnostic.VO_Treatment TreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDiagnostic.VO_Doctor DoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDiagnostic.VO_Patient PatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDiagnostic.VO_Laboratory_Result LabResultField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDiagnostic {
            get {
                return this.IdDiagnosticField;
            }
            set {
                if ((this.IdDiagnosticField.Equals(value) != true)) {
                    this.IdDiagnosticField = value;
                    this.RaisePropertyChanged("IdDiagnostic");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string MedicalCondition {
            get {
                return this.MedicalConditionField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicalConditionField, value) != true)) {
                    this.MedicalConditionField = value;
                    this.RaisePropertyChanged("MedicalCondition");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RegisterDate {
            get {
                return this.RegisterDateField;
            }
            set {
                if ((object.ReferenceEquals(this.RegisterDateField, value) != true)) {
                    this.RegisterDateField = value;
                    this.RaisePropertyChanged("RegisterDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public WSClient.ServiceDiagnostic.VO_Treatment Treatment {
            get {
                return this.TreatmentField;
            }
            set {
                if ((object.ReferenceEquals(this.TreatmentField, value) != true)) {
                    this.TreatmentField = value;
                    this.RaisePropertyChanged("Treatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public WSClient.ServiceDiagnostic.VO_Doctor Doctor {
            get {
                return this.DoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.DoctorField, value) != true)) {
                    this.DoctorField = value;
                    this.RaisePropertyChanged("Doctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public WSClient.ServiceDiagnostic.VO_Patient Patient {
            get {
                return this.PatientField;
            }
            set {
                if ((object.ReferenceEquals(this.PatientField, value) != true)) {
                    this.PatientField = value;
                    this.RaisePropertyChanged("Patient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WSClient.ServiceDiagnostic.VO_Laboratory_Result LabResult {
            get {
                return this.LabResultField;
            }
            set {
                if ((object.ReferenceEquals(this.LabResultField, value) != true)) {
                    this.LabResultField = value;
                    this.RaisePropertyChanged("LabResult");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Treatment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Treatment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecommendTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDiagnostic.VO_Medicament MedicamentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTreatment {
            get {
                return this.IdTreatmentField;
            }
            set {
                if ((this.IdTreatmentField.Equals(value) != true)) {
                    this.IdTreatmentField = value;
                    this.RaisePropertyChanged("IdTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecommendTreatment {
            get {
                return this.RecommendTreatmentField;
            }
            set {
                if ((object.ReferenceEquals(this.RecommendTreatmentField, value) != true)) {
                    this.RecommendTreatmentField = value;
                    this.RaisePropertyChanged("RecommendTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StartedDate {
            get {
                return this.StartedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartedDateField, value) != true)) {
                    this.StartedDateField = value;
                    this.RaisePropertyChanged("StartedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WSClient.ServiceDiagnostic.VO_Medicament Medicament {
            get {
                return this.MedicamentField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicamentField, value) != true)) {
                    this.MedicamentField = value;
                    this.RaisePropertyChanged("Medicament");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Doctor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameDoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDiagnostic.VO_Address AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDoctor {
            get {
                return this.IdDoctorField;
            }
            set {
                if ((this.IdDoctorField.Equals(value) != true)) {
                    this.IdDoctorField = value;
                    this.RaisePropertyChanged("IdDoctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameDoctor {
            get {
                return this.NameDoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.NameDoctorField, value) != true)) {
                    this.NameDoctorField = value;
                    this.RaisePropertyChanged("NameDoctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WSClient.ServiceDiagnostic.VO_Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Patient", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdPatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamePatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDiagnostic.VO_Address AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPatient {
            get {
                return this.IdPatientField;
            }
            set {
                if ((this.IdPatientField.Equals(value) != true)) {
                    this.IdPatientField = value;
                    this.RaisePropertyChanged("IdPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NamePatient {
            get {
                return this.NamePatientField;
            }
            set {
                if ((object.ReferenceEquals(this.NamePatientField, value) != true)) {
                    this.NamePatientField = value;
                    this.RaisePropertyChanged("NamePatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WSClient.ServiceDiagnostic.VO_Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Laboratory_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Laboratory_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdLaboratoryResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdLaboratoryResult {
            get {
                return this.IdLaboratoryResultField;
            }
            set {
                if ((this.IdLaboratoryResultField.Equals(value) != true)) {
                    this.IdLaboratoryResultField = value;
                    this.RaisePropertyChanged("IdLaboratoryResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Test {
            get {
                return this.TestField;
            }
            set {
                if ((object.ReferenceEquals(this.TestField, value) != true)) {
                    this.TestField = value;
                    this.RaisePropertyChanged("Test");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DateDone {
            get {
                return this.DateDoneField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDoneField, value) != true)) {
                    this.DateDoneField = value;
                    this.RaisePropertyChanged("DateDone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Medicament", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Medicament : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdMedicamentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameMedicamentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseInstructionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdMedicament {
            get {
                return this.IdMedicamentField;
            }
            set {
                if ((this.IdMedicamentField.Equals(value) != true)) {
                    this.IdMedicamentField = value;
                    this.RaisePropertyChanged("IdMedicament");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameMedicament {
            get {
                return this.NameMedicamentField;
            }
            set {
                if ((object.ReferenceEquals(this.NameMedicamentField, value) != true)) {
                    this.NameMedicamentField = value;
                    this.RaisePropertyChanged("NameMedicament");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dose {
            get {
                return this.DoseField;
            }
            set {
                if ((object.ReferenceEquals(this.DoseField, value) != true)) {
                    this.DoseField = value;
                    this.RaisePropertyChanged("Dose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UseInstruction {
            get {
                return this.UseInstructionField;
            }
            set {
                if ((object.ReferenceEquals(this.UseInstructionField, value) != true)) {
                    this.UseInstructionField = value;
                    this.RaisePropertyChanged("UseInstruction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdAddress {
            get {
                return this.IdAddressField;
            }
            set {
                if ((this.IdAddressField.Equals(value) != true)) {
                    this.IdAddressField = value;
                    this.RaisePropertyChanged("IdAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDiagnostic.DiagnosticServiceSoap")]
    public interface DiagnosticServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento diagnostic del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDiagnostic", ReplyAction="*")]
        WSClient.ServiceDiagnostic.CreateDiagnosticResponse CreateDiagnostic(WSClient.ServiceDiagnostic.CreateDiagnosticRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDiagnostic", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.CreateDiagnosticResponse> CreateDiagnosticAsync(WSClient.ServiceDiagnostic.CreateDiagnosticRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllDiagnosticsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDiagnostics", ReplyAction="*")]
        WSClient.ServiceDiagnostic.GetAllDiagnosticsResponse GetAllDiagnostics(WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDiagnostics", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetAllDiagnosticsResponse> GetAllDiagnosticsAsync(WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento diagnostic del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDiagnostic", ReplyAction="*")]
        WSClient.ServiceDiagnostic.UpdateDiagnosticResponse UpdateDiagnostic(WSClient.ServiceDiagnostic.UpdateDiagnosticRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDiagnostic", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.UpdateDiagnosticResponse> UpdateDiagnosticAsync(WSClient.ServiceDiagnostic.UpdateDiagnosticRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDiagnostic", ReplyAction="*")]
        bool DeleteDiagnostic(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDiagnostic", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteDiagnosticAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDiagnosticByLabIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticByLabId", ReplyAction="*")]
        WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponse GetDiagnosticByLabId(WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticByLabId", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponse> GetDiagnosticByLabIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDiagnosticByDoctorIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticByDoctorId", ReplyAction="*")]
        WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponse GetDiagnosticByDoctorId(WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticByDoctorId", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponse> GetDiagnosticByDoctorIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDiagnosticByPatientIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticByPatientId", ReplyAction="*")]
        WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponse GetDiagnosticByPatientId(WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticByPatientId", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponse> GetDiagnosticByPatientIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetDiagnosticByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticById", ReplyAction="*")]
        WSClient.ServiceDiagnostic.GetDiagnosticByIdResponse GetDiagnosticById(WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetDiagnosticById", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByIdResponse> GetDiagnosticByIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDiagnosticRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDiagnostic", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.CreateDiagnosticRequestBody Body;
        
        public CreateDiagnosticRequest() {
        }
        
        public CreateDiagnosticRequest(WSClient.ServiceDiagnostic.CreateDiagnosticRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateDiagnosticRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic;
        
        public CreateDiagnosticRequestBody() {
        }
        
        public CreateDiagnosticRequestBody(WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic) {
            this.diagnostic = diagnostic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDiagnosticResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDiagnosticResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.CreateDiagnosticResponseBody Body;
        
        public CreateDiagnosticResponse() {
        }
        
        public CreateDiagnosticResponse(WSClient.ServiceDiagnostic.CreateDiagnosticResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateDiagnosticResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateDiagnosticResult;
        
        public CreateDiagnosticResponseBody() {
        }
        
        public CreateDiagnosticResponseBody(int CreateDiagnosticResult) {
            this.CreateDiagnosticResult = CreateDiagnosticResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDiagnosticsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDiagnostics", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetAllDiagnosticsRequestBody Body;
        
        public GetAllDiagnosticsRequest() {
        }
        
        public GetAllDiagnosticsRequest(WSClient.ServiceDiagnostic.GetAllDiagnosticsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDiagnosticsRequestBody {
        
        public GetAllDiagnosticsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDiagnosticsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDiagnosticsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetAllDiagnosticsResponseBody Body;
        
        public GetAllDiagnosticsResponse() {
        }
        
        public GetAllDiagnosticsResponse(WSClient.ServiceDiagnostic.GetAllDiagnosticsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDiagnosticsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDiagnostic.VO_Diagnostic[] GetAllDiagnosticsResult;
        
        public GetAllDiagnosticsResponseBody() {
        }
        
        public GetAllDiagnosticsResponseBody(WSClient.ServiceDiagnostic.VO_Diagnostic[] GetAllDiagnosticsResult) {
            this.GetAllDiagnosticsResult = GetAllDiagnosticsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDiagnosticRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDiagnostic", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.UpdateDiagnosticRequestBody Body;
        
        public UpdateDiagnosticRequest() {
        }
        
        public UpdateDiagnosticRequest(WSClient.ServiceDiagnostic.UpdateDiagnosticRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDiagnosticRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic;
        
        public UpdateDiagnosticRequestBody() {
        }
        
        public UpdateDiagnosticRequestBody(WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic) {
            this.diagnostic = diagnostic;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDiagnosticResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDiagnosticResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.UpdateDiagnosticResponseBody Body;
        
        public UpdateDiagnosticResponse() {
        }
        
        public UpdateDiagnosticResponse(WSClient.ServiceDiagnostic.UpdateDiagnosticResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDiagnosticResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateDiagnosticResult;
        
        public UpdateDiagnosticResponseBody() {
        }
        
        public UpdateDiagnosticResponseBody(bool UpdateDiagnosticResult) {
            this.UpdateDiagnosticResult = UpdateDiagnosticResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByLabIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticByLabId", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequestBody Body;
        
        public GetDiagnosticByLabIdRequest() {
        }
        
        public GetDiagnosticByLabIdRequest(WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByLabIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetDiagnosticByLabIdRequestBody() {
        }
        
        public GetDiagnosticByLabIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByLabIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticByLabIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponseBody Body;
        
        public GetDiagnosticByLabIdResponse() {
        }
        
        public GetDiagnosticByLabIdResponse(WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByLabIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByLabIdResult;
        
        public GetDiagnosticByLabIdResponseBody() {
        }
        
        public GetDiagnosticByLabIdResponseBody(WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByLabIdResult) {
            this.GetDiagnosticByLabIdResult = GetDiagnosticByLabIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByDoctorIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticByDoctorId", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequestBody Body;
        
        public GetDiagnosticByDoctorIdRequest() {
        }
        
        public GetDiagnosticByDoctorIdRequest(WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByDoctorIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDoctor;
        
        public GetDiagnosticByDoctorIdRequestBody() {
        }
        
        public GetDiagnosticByDoctorIdRequestBody(int idDoctor) {
            this.idDoctor = idDoctor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByDoctorIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticByDoctorIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponseBody Body;
        
        public GetDiagnosticByDoctorIdResponse() {
        }
        
        public GetDiagnosticByDoctorIdResponse(WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByDoctorIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByDoctorIdResult;
        
        public GetDiagnosticByDoctorIdResponseBody() {
        }
        
        public GetDiagnosticByDoctorIdResponseBody(WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByDoctorIdResult) {
            this.GetDiagnosticByDoctorIdResult = GetDiagnosticByDoctorIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByPatientIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticByPatientId", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequestBody Body;
        
        public GetDiagnosticByPatientIdRequest() {
        }
        
        public GetDiagnosticByPatientIdRequest(WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByPatientIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDoctor;
        
        public GetDiagnosticByPatientIdRequestBody() {
        }
        
        public GetDiagnosticByPatientIdRequestBody(int idDoctor) {
            this.idDoctor = idDoctor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByPatientIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticByPatientIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponseBody Body;
        
        public GetDiagnosticByPatientIdResponse() {
        }
        
        public GetDiagnosticByPatientIdResponse(WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByPatientIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByPatientIdResult;
        
        public GetDiagnosticByPatientIdResponseBody() {
        }
        
        public GetDiagnosticByPatientIdResponseBody(WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByPatientIdResult) {
            this.GetDiagnosticByPatientIdResult = GetDiagnosticByPatientIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticById", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByIdRequestBody Body;
        
        public GetDiagnosticByIdRequest() {
        }
        
        public GetDiagnosticByIdRequest(WSClient.ServiceDiagnostic.GetDiagnosticByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDoctor;
        
        public GetDiagnosticByIdRequestBody() {
        }
        
        public GetDiagnosticByIdRequestBody(int idDoctor) {
            this.idDoctor = idDoctor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetDiagnosticByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetDiagnosticByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDiagnostic.GetDiagnosticByIdResponseBody Body;
        
        public GetDiagnosticByIdResponse() {
        }
        
        public GetDiagnosticByIdResponse(WSClient.ServiceDiagnostic.GetDiagnosticByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetDiagnosticByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByIdResult;
        
        public GetDiagnosticByIdResponseBody() {
        }
        
        public GetDiagnosticByIdResponseBody(WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByIdResult) {
            this.GetDiagnosticByIdResult = GetDiagnosticByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DiagnosticServiceSoapChannel : WSClient.ServiceDiagnostic.DiagnosticServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DiagnosticServiceSoapClient : System.ServiceModel.ClientBase<WSClient.ServiceDiagnostic.DiagnosticServiceSoap>, WSClient.ServiceDiagnostic.DiagnosticServiceSoap {
        
        public DiagnosticServiceSoapClient() {
        }
        
        public DiagnosticServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DiagnosticServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DiagnosticServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDiagnostic.CreateDiagnosticResponse WSClient.ServiceDiagnostic.DiagnosticServiceSoap.CreateDiagnostic(WSClient.ServiceDiagnostic.CreateDiagnosticRequest request) {
            return base.Channel.CreateDiagnostic(request);
        }
        
        public int CreateDiagnostic(WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic) {
            WSClient.ServiceDiagnostic.CreateDiagnosticRequest inValue = new WSClient.ServiceDiagnostic.CreateDiagnosticRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.CreateDiagnosticRequestBody();
            inValue.Body.diagnostic = diagnostic;
            WSClient.ServiceDiagnostic.CreateDiagnosticResponse retVal = ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).CreateDiagnostic(inValue);
            return retVal.Body.CreateDiagnosticResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.CreateDiagnosticResponse> WSClient.ServiceDiagnostic.DiagnosticServiceSoap.CreateDiagnosticAsync(WSClient.ServiceDiagnostic.CreateDiagnosticRequest request) {
            return base.Channel.CreateDiagnosticAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.CreateDiagnosticResponse> CreateDiagnosticAsync(WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic) {
            WSClient.ServiceDiagnostic.CreateDiagnosticRequest inValue = new WSClient.ServiceDiagnostic.CreateDiagnosticRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.CreateDiagnosticRequestBody();
            inValue.Body.diagnostic = diagnostic;
            return ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).CreateDiagnosticAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDiagnostic.GetAllDiagnosticsResponse WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetAllDiagnostics(WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest request) {
            return base.Channel.GetAllDiagnostics(request);
        }
        
        public WSClient.ServiceDiagnostic.VO_Diagnostic[] GetAllDiagnostics() {
            WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest inValue = new WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetAllDiagnosticsRequestBody();
            WSClient.ServiceDiagnostic.GetAllDiagnosticsResponse retVal = ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetAllDiagnostics(inValue);
            return retVal.Body.GetAllDiagnosticsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetAllDiagnosticsResponse> WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetAllDiagnosticsAsync(WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest request) {
            return base.Channel.GetAllDiagnosticsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetAllDiagnosticsResponse> GetAllDiagnosticsAsync() {
            WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest inValue = new WSClient.ServiceDiagnostic.GetAllDiagnosticsRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetAllDiagnosticsRequestBody();
            return ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetAllDiagnosticsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDiagnostic.UpdateDiagnosticResponse WSClient.ServiceDiagnostic.DiagnosticServiceSoap.UpdateDiagnostic(WSClient.ServiceDiagnostic.UpdateDiagnosticRequest request) {
            return base.Channel.UpdateDiagnostic(request);
        }
        
        public bool UpdateDiagnostic(WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic) {
            WSClient.ServiceDiagnostic.UpdateDiagnosticRequest inValue = new WSClient.ServiceDiagnostic.UpdateDiagnosticRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.UpdateDiagnosticRequestBody();
            inValue.Body.diagnostic = diagnostic;
            WSClient.ServiceDiagnostic.UpdateDiagnosticResponse retVal = ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).UpdateDiagnostic(inValue);
            return retVal.Body.UpdateDiagnosticResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.UpdateDiagnosticResponse> WSClient.ServiceDiagnostic.DiagnosticServiceSoap.UpdateDiagnosticAsync(WSClient.ServiceDiagnostic.UpdateDiagnosticRequest request) {
            return base.Channel.UpdateDiagnosticAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.UpdateDiagnosticResponse> UpdateDiagnosticAsync(WSClient.ServiceDiagnostic.VO_Diagnostic diagnostic) {
            WSClient.ServiceDiagnostic.UpdateDiagnosticRequest inValue = new WSClient.ServiceDiagnostic.UpdateDiagnosticRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.UpdateDiagnosticRequestBody();
            inValue.Body.diagnostic = diagnostic;
            return ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).UpdateDiagnosticAsync(inValue);
        }
        
        public bool DeleteDiagnostic(int id) {
            return base.Channel.DeleteDiagnostic(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDiagnosticAsync(int id) {
            return base.Channel.DeleteDiagnosticAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponse WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticByLabId(WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest request) {
            return base.Channel.GetDiagnosticByLabId(request);
        }
        
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByLabId(int id) {
            WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequestBody();
            inValue.Body.id = id;
            WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponse retVal = ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticByLabId(inValue);
            return retVal.Body.GetDiagnosticByLabIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponse> WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticByLabIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest request) {
            return base.Channel.GetDiagnosticByLabIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByLabIdResponse> GetDiagnosticByLabIdAsync(int id) {
            WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByLabIdRequestBody();
            inValue.Body.id = id;
            return ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticByLabIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponse WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticByDoctorId(WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest request) {
            return base.Channel.GetDiagnosticByDoctorId(request);
        }
        
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByDoctorId(int idDoctor) {
            WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponse retVal = ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticByDoctorId(inValue);
            return retVal.Body.GetDiagnosticByDoctorIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponse> WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticByDoctorIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest request) {
            return base.Channel.GetDiagnosticByDoctorIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdResponse> GetDiagnosticByDoctorIdAsync(int idDoctor) {
            WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByDoctorIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            return ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticByDoctorIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponse WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticByPatientId(WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest request) {
            return base.Channel.GetDiagnosticByPatientId(request);
        }
        
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticByPatientId(int idDoctor) {
            WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponse retVal = ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticByPatientId(inValue);
            return retVal.Body.GetDiagnosticByPatientIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponse> WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticByPatientIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest request) {
            return base.Channel.GetDiagnosticByPatientIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdResponse> GetDiagnosticByPatientIdAsync(int idDoctor) {
            WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByPatientIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            return ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticByPatientIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDiagnostic.GetDiagnosticByIdResponse WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticById(WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest request) {
            return base.Channel.GetDiagnosticById(request);
        }
        
        public WSClient.ServiceDiagnostic.VO_Diagnostic GetDiagnosticById(int idDoctor) {
            WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            WSClient.ServiceDiagnostic.GetDiagnosticByIdResponse retVal = ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticById(inValue);
            return retVal.Body.GetDiagnosticByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByIdResponse> WSClient.ServiceDiagnostic.DiagnosticServiceSoap.GetDiagnosticByIdAsync(WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest request) {
            return base.Channel.GetDiagnosticByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDiagnostic.GetDiagnosticByIdResponse> GetDiagnosticByIdAsync(int idDoctor) {
            WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest inValue = new WSClient.ServiceDiagnostic.GetDiagnosticByIdRequest();
            inValue.Body = new WSClient.ServiceDiagnostic.GetDiagnosticByIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            return ((WSClient.ServiceDiagnostic.DiagnosticServiceSoap)(this)).GetDiagnosticByIdAsync(inValue);
        }
    }
}
