//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServiceAddress {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdAddress {
            get {
                return this.IdAddressField;
            }
            set {
                if ((this.IdAddressField.Equals(value) != true)) {
                    this.IdAddressField = value;
                    this.RaisePropertyChanged("IdAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.CollectionDataContractAttribute(Name="ArrayOfAnyType", Namespace="http://tempuri.org/", ItemName="anyType")]
    [System.SerializableAttribute()]
    public class ArrayOfAnyType : System.Collections.Generic.List<object> {
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceAddress.AddressServiceSoap")]
    public interface AddressServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento address del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAddress", ReplyAction="*")]
        WSClient.ServiceAddress.CreateAddressResponse CreateAddress(WSClient.ServiceAddress.CreateAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.CreateAddressResponse> CreateAddressAsync(WSClient.ServiceAddress.CreateAddressRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento parameters del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAddresss", ReplyAction="*")]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSClient.ServiceAddress.VO_Address))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSClient.ServiceAddress.ArrayOfAnyType))]
        [System.ServiceModel.ServiceKnownTypeAttribute(typeof(WSClient.ServiceAddress.VO_Address[]))]
        WSClient.ServiceAddress.ListAddresssResponse ListAddresss(WSClient.ServiceAddress.ListAddresssRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAddresss", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.ListAddresssResponse> ListAddresssAsync(WSClient.ServiceAddress.ListAddresssRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAddressByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressById", ReplyAction="*")]
        WSClient.ServiceAddress.GetAddressByIdResponse GetAddressById(WSClient.ServiceAddress.GetAddressByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAddressById", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.GetAddressByIdResponse> GetAddressByIdAsync(WSClient.ServiceAddress.GetAddressByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento address del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAddress", ReplyAction="*")]
        WSClient.ServiceAddress.UpdateAddressResponse UpdateAddress(WSClient.ServiceAddress.UpdateAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.UpdateAddressResponse> UpdateAddressAsync(WSClient.ServiceAddress.UpdateAddressRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DeleteAddressResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAddress", ReplyAction="*")]
        WSClient.ServiceAddress.DeleteAddressResponse DeleteAddress(WSClient.ServiceAddress.DeleteAddressRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteAddress", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.DeleteAddressResponse> DeleteAddressAsync(WSClient.ServiceAddress.DeleteAddressRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListAddressCompleteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAddressComplete", ReplyAction="*")]
        WSClient.ServiceAddress.ListAddressCompleteResponse ListAddressComplete(WSClient.ServiceAddress.ListAddressCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListAddressComplete", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.ListAddressCompleteResponse> ListAddressCompleteAsync(WSClient.ServiceAddress.ListAddressCompleteRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAddress", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.CreateAddressRequestBody Body;
        
        public CreateAddressRequest() {
        }
        
        public CreateAddressRequest(WSClient.ServiceAddress.CreateAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceAddress.VO_Address address;
        
        public CreateAddressRequestBody() {
        }
        
        public CreateAddressRequestBody(WSClient.ServiceAddress.VO_Address address) {
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.CreateAddressResponseBody Body;
        
        public CreateAddressResponse() {
        }
        
        public CreateAddressResponse(WSClient.ServiceAddress.CreateAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateAddressResult;
        
        public CreateAddressResponseBody() {
        }
        
        public CreateAddressResponseBody(string CreateAddressResult) {
            this.CreateAddressResult = CreateAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAddresssRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAddresss", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.ListAddresssRequestBody Body;
        
        public ListAddresssRequest() {
        }
        
        public ListAddresssRequest(WSClient.ServiceAddress.ListAddresssRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAddresssRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceAddress.ArrayOfAnyType parameters;
        
        public ListAddresssRequestBody() {
        }
        
        public ListAddresssRequestBody(WSClient.ServiceAddress.ArrayOfAnyType parameters) {
            this.parameters = parameters;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAddresssResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAddresssResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.ListAddresssResponseBody Body;
        
        public ListAddresssResponse() {
        }
        
        public ListAddresssResponse(WSClient.ServiceAddress.ListAddresssResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAddresssResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceAddress.VO_Address[] ListAddresssResult;
        
        public ListAddresssResponseBody() {
        }
        
        public ListAddresssResponseBody(WSClient.ServiceAddress.VO_Address[] ListAddresssResult) {
            this.ListAddresssResult = ListAddresssResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressById", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.GetAddressByIdRequestBody Body;
        
        public GetAddressByIdRequest() {
        }
        
        public GetAddressByIdRequest(WSClient.ServiceAddress.GetAddressByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetAddressByIdRequestBody() {
        }
        
        public GetAddressByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAddressByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAddressByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.GetAddressByIdResponseBody Body;
        
        public GetAddressByIdResponse() {
        }
        
        public GetAddressByIdResponse(WSClient.ServiceAddress.GetAddressByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAddressByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceAddress.VO_Address GetAddressByIdResult;
        
        public GetAddressByIdResponseBody() {
        }
        
        public GetAddressByIdResponseBody(WSClient.ServiceAddress.VO_Address GetAddressByIdResult) {
            this.GetAddressByIdResult = GetAddressByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAddress", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.UpdateAddressRequestBody Body;
        
        public UpdateAddressRequest() {
        }
        
        public UpdateAddressRequest(WSClient.ServiceAddress.UpdateAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceAddress.VO_Address address;
        
        public UpdateAddressRequestBody() {
        }
        
        public UpdateAddressRequestBody(WSClient.ServiceAddress.VO_Address address) {
            this.address = address;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.UpdateAddressResponseBody Body;
        
        public UpdateAddressResponse() {
        }
        
        public UpdateAddressResponse(WSClient.ServiceAddress.UpdateAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateAddressResult;
        
        public UpdateAddressResponseBody() {
        }
        
        public UpdateAddressResponseBody(string UpdateAddressResult) {
            this.UpdateAddressResult = UpdateAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAddressRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAddress", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.DeleteAddressRequestBody Body;
        
        public DeleteAddressRequest() {
        }
        
        public DeleteAddressRequest(WSClient.ServiceAddress.DeleteAddressRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteAddressRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public DeleteAddressRequestBody() {
        }
        
        public DeleteAddressRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteAddressResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteAddressResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.DeleteAddressResponseBody Body;
        
        public DeleteAddressResponse() {
        }
        
        public DeleteAddressResponse(WSClient.ServiceAddress.DeleteAddressResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteAddressResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteAddressResult;
        
        public DeleteAddressResponseBody() {
        }
        
        public DeleteAddressResponseBody(string DeleteAddressResult) {
            this.DeleteAddressResult = DeleteAddressResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAddressCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAddressComplete", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.ListAddressCompleteRequestBody Body;
        
        public ListAddressCompleteRequest() {
        }
        
        public ListAddressCompleteRequest(WSClient.ServiceAddress.ListAddressCompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListAddressCompleteRequestBody {
        
        public ListAddressCompleteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListAddressCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListAddressCompleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceAddress.ListAddressCompleteResponseBody Body;
        
        public ListAddressCompleteResponse() {
        }
        
        public ListAddressCompleteResponse(WSClient.ServiceAddress.ListAddressCompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListAddressCompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceAddress.VO_Address[] ListAddressCompleteResult;
        
        public ListAddressCompleteResponseBody() {
        }
        
        public ListAddressCompleteResponseBody(WSClient.ServiceAddress.VO_Address[] ListAddressCompleteResult) {
            this.ListAddressCompleteResult = ListAddressCompleteResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface AddressServiceSoapChannel : WSClient.ServiceAddress.AddressServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class AddressServiceSoapClient : System.ServiceModel.ClientBase<WSClient.ServiceAddress.AddressServiceSoap>, WSClient.ServiceAddress.AddressServiceSoap {
        
        public AddressServiceSoapClient() {
        }
        
        public AddressServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public AddressServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public AddressServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceAddress.CreateAddressResponse WSClient.ServiceAddress.AddressServiceSoap.CreateAddress(WSClient.ServiceAddress.CreateAddressRequest request) {
            return base.Channel.CreateAddress(request);
        }
        
        public string CreateAddress(WSClient.ServiceAddress.VO_Address address) {
            WSClient.ServiceAddress.CreateAddressRequest inValue = new WSClient.ServiceAddress.CreateAddressRequest();
            inValue.Body = new WSClient.ServiceAddress.CreateAddressRequestBody();
            inValue.Body.address = address;
            WSClient.ServiceAddress.CreateAddressResponse retVal = ((WSClient.ServiceAddress.AddressServiceSoap)(this)).CreateAddress(inValue);
            return retVal.Body.CreateAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.CreateAddressResponse> WSClient.ServiceAddress.AddressServiceSoap.CreateAddressAsync(WSClient.ServiceAddress.CreateAddressRequest request) {
            return base.Channel.CreateAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceAddress.CreateAddressResponse> CreateAddressAsync(WSClient.ServiceAddress.VO_Address address) {
            WSClient.ServiceAddress.CreateAddressRequest inValue = new WSClient.ServiceAddress.CreateAddressRequest();
            inValue.Body = new WSClient.ServiceAddress.CreateAddressRequestBody();
            inValue.Body.address = address;
            return ((WSClient.ServiceAddress.AddressServiceSoap)(this)).CreateAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceAddress.ListAddresssResponse WSClient.ServiceAddress.AddressServiceSoap.ListAddresss(WSClient.ServiceAddress.ListAddresssRequest request) {
            return base.Channel.ListAddresss(request);
        }
        
        public WSClient.ServiceAddress.VO_Address[] ListAddresss(WSClient.ServiceAddress.ArrayOfAnyType parameters) {
            WSClient.ServiceAddress.ListAddresssRequest inValue = new WSClient.ServiceAddress.ListAddresssRequest();
            inValue.Body = new WSClient.ServiceAddress.ListAddresssRequestBody();
            inValue.Body.parameters = parameters;
            WSClient.ServiceAddress.ListAddresssResponse retVal = ((WSClient.ServiceAddress.AddressServiceSoap)(this)).ListAddresss(inValue);
            return retVal.Body.ListAddresssResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.ListAddresssResponse> WSClient.ServiceAddress.AddressServiceSoap.ListAddresssAsync(WSClient.ServiceAddress.ListAddresssRequest request) {
            return base.Channel.ListAddresssAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceAddress.ListAddresssResponse> ListAddresssAsync(WSClient.ServiceAddress.ArrayOfAnyType parameters) {
            WSClient.ServiceAddress.ListAddresssRequest inValue = new WSClient.ServiceAddress.ListAddresssRequest();
            inValue.Body = new WSClient.ServiceAddress.ListAddresssRequestBody();
            inValue.Body.parameters = parameters;
            return ((WSClient.ServiceAddress.AddressServiceSoap)(this)).ListAddresssAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceAddress.GetAddressByIdResponse WSClient.ServiceAddress.AddressServiceSoap.GetAddressById(WSClient.ServiceAddress.GetAddressByIdRequest request) {
            return base.Channel.GetAddressById(request);
        }
        
        public WSClient.ServiceAddress.VO_Address GetAddressById(int id) {
            WSClient.ServiceAddress.GetAddressByIdRequest inValue = new WSClient.ServiceAddress.GetAddressByIdRequest();
            inValue.Body = new WSClient.ServiceAddress.GetAddressByIdRequestBody();
            inValue.Body.id = id;
            WSClient.ServiceAddress.GetAddressByIdResponse retVal = ((WSClient.ServiceAddress.AddressServiceSoap)(this)).GetAddressById(inValue);
            return retVal.Body.GetAddressByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.GetAddressByIdResponse> WSClient.ServiceAddress.AddressServiceSoap.GetAddressByIdAsync(WSClient.ServiceAddress.GetAddressByIdRequest request) {
            return base.Channel.GetAddressByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceAddress.GetAddressByIdResponse> GetAddressByIdAsync(int id) {
            WSClient.ServiceAddress.GetAddressByIdRequest inValue = new WSClient.ServiceAddress.GetAddressByIdRequest();
            inValue.Body = new WSClient.ServiceAddress.GetAddressByIdRequestBody();
            inValue.Body.id = id;
            return ((WSClient.ServiceAddress.AddressServiceSoap)(this)).GetAddressByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceAddress.UpdateAddressResponse WSClient.ServiceAddress.AddressServiceSoap.UpdateAddress(WSClient.ServiceAddress.UpdateAddressRequest request) {
            return base.Channel.UpdateAddress(request);
        }
        
        public string UpdateAddress(WSClient.ServiceAddress.VO_Address address) {
            WSClient.ServiceAddress.UpdateAddressRequest inValue = new WSClient.ServiceAddress.UpdateAddressRequest();
            inValue.Body = new WSClient.ServiceAddress.UpdateAddressRequestBody();
            inValue.Body.address = address;
            WSClient.ServiceAddress.UpdateAddressResponse retVal = ((WSClient.ServiceAddress.AddressServiceSoap)(this)).UpdateAddress(inValue);
            return retVal.Body.UpdateAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.UpdateAddressResponse> WSClient.ServiceAddress.AddressServiceSoap.UpdateAddressAsync(WSClient.ServiceAddress.UpdateAddressRequest request) {
            return base.Channel.UpdateAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceAddress.UpdateAddressResponse> UpdateAddressAsync(WSClient.ServiceAddress.VO_Address address) {
            WSClient.ServiceAddress.UpdateAddressRequest inValue = new WSClient.ServiceAddress.UpdateAddressRequest();
            inValue.Body = new WSClient.ServiceAddress.UpdateAddressRequestBody();
            inValue.Body.address = address;
            return ((WSClient.ServiceAddress.AddressServiceSoap)(this)).UpdateAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceAddress.DeleteAddressResponse WSClient.ServiceAddress.AddressServiceSoap.DeleteAddress(WSClient.ServiceAddress.DeleteAddressRequest request) {
            return base.Channel.DeleteAddress(request);
        }
        
        public string DeleteAddress(int id) {
            WSClient.ServiceAddress.DeleteAddressRequest inValue = new WSClient.ServiceAddress.DeleteAddressRequest();
            inValue.Body = new WSClient.ServiceAddress.DeleteAddressRequestBody();
            inValue.Body.id = id;
            WSClient.ServiceAddress.DeleteAddressResponse retVal = ((WSClient.ServiceAddress.AddressServiceSoap)(this)).DeleteAddress(inValue);
            return retVal.Body.DeleteAddressResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.DeleteAddressResponse> WSClient.ServiceAddress.AddressServiceSoap.DeleteAddressAsync(WSClient.ServiceAddress.DeleteAddressRequest request) {
            return base.Channel.DeleteAddressAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceAddress.DeleteAddressResponse> DeleteAddressAsync(int id) {
            WSClient.ServiceAddress.DeleteAddressRequest inValue = new WSClient.ServiceAddress.DeleteAddressRequest();
            inValue.Body = new WSClient.ServiceAddress.DeleteAddressRequestBody();
            inValue.Body.id = id;
            return ((WSClient.ServiceAddress.AddressServiceSoap)(this)).DeleteAddressAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceAddress.ListAddressCompleteResponse WSClient.ServiceAddress.AddressServiceSoap.ListAddressComplete(WSClient.ServiceAddress.ListAddressCompleteRequest request) {
            return base.Channel.ListAddressComplete(request);
        }
        
        public WSClient.ServiceAddress.VO_Address[] ListAddressComplete() {
            WSClient.ServiceAddress.ListAddressCompleteRequest inValue = new WSClient.ServiceAddress.ListAddressCompleteRequest();
            inValue.Body = new WSClient.ServiceAddress.ListAddressCompleteRequestBody();
            WSClient.ServiceAddress.ListAddressCompleteResponse retVal = ((WSClient.ServiceAddress.AddressServiceSoap)(this)).ListAddressComplete(inValue);
            return retVal.Body.ListAddressCompleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceAddress.ListAddressCompleteResponse> WSClient.ServiceAddress.AddressServiceSoap.ListAddressCompleteAsync(WSClient.ServiceAddress.ListAddressCompleteRequest request) {
            return base.Channel.ListAddressCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceAddress.ListAddressCompleteResponse> ListAddressCompleteAsync() {
            WSClient.ServiceAddress.ListAddressCompleteRequest inValue = new WSClient.ServiceAddress.ListAddressCompleteRequest();
            inValue.Body = new WSClient.ServiceAddress.ListAddressCompleteRequestBody();
            return ((WSClient.ServiceAddress.AddressServiceSoap)(this)).ListAddressCompleteAsync(inValue);
        }
    }
}
