//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServiceDoctor {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Doctor", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Doctor : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdDoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameDoctorField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceDoctor.VO_Address AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdDoctor {
            get {
                return this.IdDoctorField;
            }
            set {
                if ((this.IdDoctorField.Equals(value) != true)) {
                    this.IdDoctorField = value;
                    this.RaisePropertyChanged("IdDoctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameDoctor {
            get {
                return this.NameDoctorField;
            }
            set {
                if ((object.ReferenceEquals(this.NameDoctorField, value) != true)) {
                    this.NameDoctorField = value;
                    this.RaisePropertyChanged("NameDoctor");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WSClient.ServiceDoctor.VO_Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdAddress {
            get {
                return this.IdAddressField;
            }
            set {
                if ((this.IdAddressField.Equals(value) != true)) {
                    this.IdAddressField = value;
                    this.RaisePropertyChanged("IdAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceDoctor.DoctorServiceSoap")]
    public interface DoctorServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Doctor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDoctor", ReplyAction="*")]
        WSClient.ServiceDoctor.CreateDoctorResponse CreateDoctor(WSClient.ServiceDoctor.CreateDoctorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateDoctor", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.CreateDoctorResponse> CreateDoctorAsync(WSClient.ServiceDoctor.CreateDoctorRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllDoctorsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDoctors", ReplyAction="*")]
        WSClient.ServiceDoctor.GetAllDoctorsResponse GetAllDoctors(WSClient.ServiceDoctor.GetAllDoctorsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDoctors", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.GetAllDoctorsResponse> GetAllDoctorsAsync(WSClient.ServiceDoctor.GetAllDoctorsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllDoctorsWithNameCompeteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDoctorsWithNameCompete", ReplyAction="*")]
        WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponse GetAllDoctorsWithNameCompete(WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllDoctorsWithNameCompete", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponse> GetAllDoctorsWithNameCompeteAsync(WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento Doctor del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDoctor", ReplyAction="*")]
        WSClient.ServiceDoctor.UpdateDoctorResponse UpdateDoctor(WSClient.ServiceDoctor.UpdateDoctorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateDoctor", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.UpdateDoctorResponse> UpdateDoctorAsync(WSClient.ServiceDoctor.UpdateDoctorRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDoctor", ReplyAction="*")]
        bool DeleteDoctor(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteDoctor", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteDoctorAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento searchByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchById", ReplyAction="*")]
        WSClient.ServiceDoctor.searchByIdResponse searchById(WSClient.ServiceDoctor.searchByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchById", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.searchByIdResponse> searchByIdAsync(WSClient.ServiceDoctor.searchByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDoctorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDoctor", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.CreateDoctorRequestBody Body;
        
        public CreateDoctorRequest() {
        }
        
        public CreateDoctorRequest(WSClient.ServiceDoctor.CreateDoctorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateDoctorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDoctor.VO_Doctor Doctor;
        
        public CreateDoctorRequestBody() {
        }
        
        public CreateDoctorRequestBody(WSClient.ServiceDoctor.VO_Doctor Doctor) {
            this.Doctor = Doctor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateDoctorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateDoctorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.CreateDoctorResponseBody Body;
        
        public CreateDoctorResponse() {
        }
        
        public CreateDoctorResponse(WSClient.ServiceDoctor.CreateDoctorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateDoctorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateDoctorResult;
        
        public CreateDoctorResponseBody() {
        }
        
        public CreateDoctorResponseBody(int CreateDoctorResult) {
            this.CreateDoctorResult = CreateDoctorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDoctorsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDoctors", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.GetAllDoctorsRequestBody Body;
        
        public GetAllDoctorsRequest() {
        }
        
        public GetAllDoctorsRequest(WSClient.ServiceDoctor.GetAllDoctorsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDoctorsRequestBody {
        
        public GetAllDoctorsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDoctorsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDoctorsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.GetAllDoctorsResponseBody Body;
        
        public GetAllDoctorsResponse() {
        }
        
        public GetAllDoctorsResponse(WSClient.ServiceDoctor.GetAllDoctorsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDoctorsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDoctor.VO_Doctor[] GetAllDoctorsResult;
        
        public GetAllDoctorsResponseBody() {
        }
        
        public GetAllDoctorsResponseBody(WSClient.ServiceDoctor.VO_Doctor[] GetAllDoctorsResult) {
            this.GetAllDoctorsResult = GetAllDoctorsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDoctorsWithNameCompeteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDoctorsWithNameCompete", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequestBody Body;
        
        public GetAllDoctorsWithNameCompeteRequest() {
        }
        
        public GetAllDoctorsWithNameCompeteRequest(WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllDoctorsWithNameCompeteRequestBody {
        
        public GetAllDoctorsWithNameCompeteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllDoctorsWithNameCompeteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllDoctorsWithNameCompeteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponseBody Body;
        
        public GetAllDoctorsWithNameCompeteResponse() {
        }
        
        public GetAllDoctorsWithNameCompeteResponse(WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllDoctorsWithNameCompeteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDoctor.VO_Doctor[] GetAllDoctorsWithNameCompeteResult;
        
        public GetAllDoctorsWithNameCompeteResponseBody() {
        }
        
        public GetAllDoctorsWithNameCompeteResponseBody(WSClient.ServiceDoctor.VO_Doctor[] GetAllDoctorsWithNameCompeteResult) {
            this.GetAllDoctorsWithNameCompeteResult = GetAllDoctorsWithNameCompeteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDoctorRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDoctor", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.UpdateDoctorRequestBody Body;
        
        public UpdateDoctorRequest() {
        }
        
        public UpdateDoctorRequest(WSClient.ServiceDoctor.UpdateDoctorRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDoctorRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDoctor.VO_Doctor Doctor;
        
        public UpdateDoctorRequestBody() {
        }
        
        public UpdateDoctorRequestBody(WSClient.ServiceDoctor.VO_Doctor Doctor) {
            this.Doctor = Doctor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateDoctorResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateDoctorResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.UpdateDoctorResponseBody Body;
        
        public UpdateDoctorResponse() {
        }
        
        public UpdateDoctorResponse(WSClient.ServiceDoctor.UpdateDoctorResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateDoctorResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateDoctorResult;
        
        public UpdateDoctorResponseBody() {
        }
        
        public UpdateDoctorResponseBody(bool UpdateDoctorResult) {
            this.UpdateDoctorResult = UpdateDoctorResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchById", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.searchByIdRequestBody Body;
        
        public searchByIdRequest() {
        }
        
        public searchByIdRequest(WSClient.ServiceDoctor.searchByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idDoctor;
        
        public searchByIdRequestBody() {
        }
        
        public searchByIdRequestBody(int idDoctor) {
            this.idDoctor = idDoctor;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceDoctor.searchByIdResponseBody Body;
        
        public searchByIdResponse() {
        }
        
        public searchByIdResponse(WSClient.ServiceDoctor.searchByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceDoctor.VO_Doctor searchByIdResult;
        
        public searchByIdResponseBody() {
        }
        
        public searchByIdResponseBody(WSClient.ServiceDoctor.VO_Doctor searchByIdResult) {
            this.searchByIdResult = searchByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface DoctorServiceSoapChannel : WSClient.ServiceDoctor.DoctorServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class DoctorServiceSoapClient : System.ServiceModel.ClientBase<WSClient.ServiceDoctor.DoctorServiceSoap>, WSClient.ServiceDoctor.DoctorServiceSoap {
        
        public DoctorServiceSoapClient() {
        }
        
        public DoctorServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public DoctorServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public DoctorServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDoctor.CreateDoctorResponse WSClient.ServiceDoctor.DoctorServiceSoap.CreateDoctor(WSClient.ServiceDoctor.CreateDoctorRequest request) {
            return base.Channel.CreateDoctor(request);
        }
        
        public int CreateDoctor(WSClient.ServiceDoctor.VO_Doctor Doctor) {
            WSClient.ServiceDoctor.CreateDoctorRequest inValue = new WSClient.ServiceDoctor.CreateDoctorRequest();
            inValue.Body = new WSClient.ServiceDoctor.CreateDoctorRequestBody();
            inValue.Body.Doctor = Doctor;
            WSClient.ServiceDoctor.CreateDoctorResponse retVal = ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).CreateDoctor(inValue);
            return retVal.Body.CreateDoctorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.CreateDoctorResponse> WSClient.ServiceDoctor.DoctorServiceSoap.CreateDoctorAsync(WSClient.ServiceDoctor.CreateDoctorRequest request) {
            return base.Channel.CreateDoctorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDoctor.CreateDoctorResponse> CreateDoctorAsync(WSClient.ServiceDoctor.VO_Doctor Doctor) {
            WSClient.ServiceDoctor.CreateDoctorRequest inValue = new WSClient.ServiceDoctor.CreateDoctorRequest();
            inValue.Body = new WSClient.ServiceDoctor.CreateDoctorRequestBody();
            inValue.Body.Doctor = Doctor;
            return ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).CreateDoctorAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDoctor.GetAllDoctorsResponse WSClient.ServiceDoctor.DoctorServiceSoap.GetAllDoctors(WSClient.ServiceDoctor.GetAllDoctorsRequest request) {
            return base.Channel.GetAllDoctors(request);
        }
        
        public WSClient.ServiceDoctor.VO_Doctor[] GetAllDoctors() {
            WSClient.ServiceDoctor.GetAllDoctorsRequest inValue = new WSClient.ServiceDoctor.GetAllDoctorsRequest();
            inValue.Body = new WSClient.ServiceDoctor.GetAllDoctorsRequestBody();
            WSClient.ServiceDoctor.GetAllDoctorsResponse retVal = ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).GetAllDoctors(inValue);
            return retVal.Body.GetAllDoctorsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.GetAllDoctorsResponse> WSClient.ServiceDoctor.DoctorServiceSoap.GetAllDoctorsAsync(WSClient.ServiceDoctor.GetAllDoctorsRequest request) {
            return base.Channel.GetAllDoctorsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDoctor.GetAllDoctorsResponse> GetAllDoctorsAsync() {
            WSClient.ServiceDoctor.GetAllDoctorsRequest inValue = new WSClient.ServiceDoctor.GetAllDoctorsRequest();
            inValue.Body = new WSClient.ServiceDoctor.GetAllDoctorsRequestBody();
            return ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).GetAllDoctorsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponse WSClient.ServiceDoctor.DoctorServiceSoap.GetAllDoctorsWithNameCompete(WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest request) {
            return base.Channel.GetAllDoctorsWithNameCompete(request);
        }
        
        public WSClient.ServiceDoctor.VO_Doctor[] GetAllDoctorsWithNameCompete() {
            WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest inValue = new WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest();
            inValue.Body = new WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequestBody();
            WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponse retVal = ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).GetAllDoctorsWithNameCompete(inValue);
            return retVal.Body.GetAllDoctorsWithNameCompeteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponse> WSClient.ServiceDoctor.DoctorServiceSoap.GetAllDoctorsWithNameCompeteAsync(WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest request) {
            return base.Channel.GetAllDoctorsWithNameCompeteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteResponse> GetAllDoctorsWithNameCompeteAsync() {
            WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest inValue = new WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequest();
            inValue.Body = new WSClient.ServiceDoctor.GetAllDoctorsWithNameCompeteRequestBody();
            return ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).GetAllDoctorsWithNameCompeteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDoctor.UpdateDoctorResponse WSClient.ServiceDoctor.DoctorServiceSoap.UpdateDoctor(WSClient.ServiceDoctor.UpdateDoctorRequest request) {
            return base.Channel.UpdateDoctor(request);
        }
        
        public bool UpdateDoctor(WSClient.ServiceDoctor.VO_Doctor Doctor) {
            WSClient.ServiceDoctor.UpdateDoctorRequest inValue = new WSClient.ServiceDoctor.UpdateDoctorRequest();
            inValue.Body = new WSClient.ServiceDoctor.UpdateDoctorRequestBody();
            inValue.Body.Doctor = Doctor;
            WSClient.ServiceDoctor.UpdateDoctorResponse retVal = ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).UpdateDoctor(inValue);
            return retVal.Body.UpdateDoctorResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.UpdateDoctorResponse> WSClient.ServiceDoctor.DoctorServiceSoap.UpdateDoctorAsync(WSClient.ServiceDoctor.UpdateDoctorRequest request) {
            return base.Channel.UpdateDoctorAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDoctor.UpdateDoctorResponse> UpdateDoctorAsync(WSClient.ServiceDoctor.VO_Doctor Doctor) {
            WSClient.ServiceDoctor.UpdateDoctorRequest inValue = new WSClient.ServiceDoctor.UpdateDoctorRequest();
            inValue.Body = new WSClient.ServiceDoctor.UpdateDoctorRequestBody();
            inValue.Body.Doctor = Doctor;
            return ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).UpdateDoctorAsync(inValue);
        }
        
        public bool DeleteDoctor(int id) {
            return base.Channel.DeleteDoctor(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteDoctorAsync(int id) {
            return base.Channel.DeleteDoctorAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceDoctor.searchByIdResponse WSClient.ServiceDoctor.DoctorServiceSoap.searchById(WSClient.ServiceDoctor.searchByIdRequest request) {
            return base.Channel.searchById(request);
        }
        
        public WSClient.ServiceDoctor.VO_Doctor searchById(int idDoctor) {
            WSClient.ServiceDoctor.searchByIdRequest inValue = new WSClient.ServiceDoctor.searchByIdRequest();
            inValue.Body = new WSClient.ServiceDoctor.searchByIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            WSClient.ServiceDoctor.searchByIdResponse retVal = ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).searchById(inValue);
            return retVal.Body.searchByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceDoctor.searchByIdResponse> WSClient.ServiceDoctor.DoctorServiceSoap.searchByIdAsync(WSClient.ServiceDoctor.searchByIdRequest request) {
            return base.Channel.searchByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceDoctor.searchByIdResponse> searchByIdAsync(int idDoctor) {
            WSClient.ServiceDoctor.searchByIdRequest inValue = new WSClient.ServiceDoctor.searchByIdRequest();
            inValue.Body = new WSClient.ServiceDoctor.searchByIdRequestBody();
            inValue.Body.idDoctor = idDoctor;
            return ((WSClient.ServiceDoctor.DoctorServiceSoap)(this)).searchByIdAsync(inValue);
        }
    }
}
