//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServicePatient {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Patient", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Patient : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdPatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NamePatientField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string MiddleNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string LastNameField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string BirthDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TelephoneField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServicePatient.VO_Address AddressField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdPatient {
            get {
                return this.IdPatientField;
            }
            set {
                if ((this.IdPatientField.Equals(value) != true)) {
                    this.IdPatientField = value;
                    this.RaisePropertyChanged("IdPatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NamePatient {
            get {
                return this.NamePatientField;
            }
            set {
                if ((object.ReferenceEquals(this.NamePatientField, value) != true)) {
                    this.NamePatientField = value;
                    this.RaisePropertyChanged("NamePatient");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string MiddleName {
            get {
                return this.MiddleNameField;
            }
            set {
                if ((object.ReferenceEquals(this.MiddleNameField, value) != true)) {
                    this.MiddleNameField = value;
                    this.RaisePropertyChanged("MiddleName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string LastName {
            get {
                return this.LastNameField;
            }
            set {
                if ((object.ReferenceEquals(this.LastNameField, value) != true)) {
                    this.LastNameField = value;
                    this.RaisePropertyChanged("LastName");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string BirthDate {
            get {
                return this.BirthDateField;
            }
            set {
                if ((object.ReferenceEquals(this.BirthDateField, value) != true)) {
                    this.BirthDateField = value;
                    this.RaisePropertyChanged("BirthDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=5)]
        public string Telephone {
            get {
                return this.TelephoneField;
            }
            set {
                if ((object.ReferenceEquals(this.TelephoneField, value) != true)) {
                    this.TelephoneField = value;
                    this.RaisePropertyChanged("Telephone");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=6)]
        public WSClient.ServicePatient.VO_Address Address {
            get {
                return this.AddressField;
            }
            set {
                if ((object.ReferenceEquals(this.AddressField, value) != true)) {
                    this.AddressField = value;
                    this.RaisePropertyChanged("Address");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Address", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Address : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdAddressField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StreetField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string SuburbField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string CityField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StateField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdAddress {
            get {
                return this.IdAddressField;
            }
            set {
                if ((this.IdAddressField.Equals(value) != true)) {
                    this.IdAddressField = value;
                    this.RaisePropertyChanged("IdAddress");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Street {
            get {
                return this.StreetField;
            }
            set {
                if ((object.ReferenceEquals(this.StreetField, value) != true)) {
                    this.StreetField = value;
                    this.RaisePropertyChanged("Street");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Suburb {
            get {
                return this.SuburbField;
            }
            set {
                if ((object.ReferenceEquals(this.SuburbField, value) != true)) {
                    this.SuburbField = value;
                    this.RaisePropertyChanged("Suburb");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string City {
            get {
                return this.CityField;
            }
            set {
                if ((object.ReferenceEquals(this.CityField, value) != true)) {
                    this.CityField = value;
                    this.RaisePropertyChanged("City");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=4)]
        public string State {
            get {
                return this.StateField;
            }
            set {
                if ((object.ReferenceEquals(this.StateField, value) != true)) {
                    this.StateField = value;
                    this.RaisePropertyChanged("State");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicePatient.PatientServiceSoap")]
    public interface PatientServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento patient del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePatient", ReplyAction="*")]
        WSClient.ServicePatient.CreatePatientResponse CreatePatient(WSClient.ServicePatient.CreatePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreatePatient", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServicePatient.CreatePatientResponse> CreatePatientAsync(WSClient.ServicePatient.CreatePatientRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllPatientsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPatients", ReplyAction="*")]
        WSClient.ServicePatient.GetAllPatientsResponse GetAllPatients(WSClient.ServicePatient.GetAllPatientsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPatients", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServicePatient.GetAllPatientsResponse> GetAllPatientsAsync(WSClient.ServicePatient.GetAllPatientsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllPatientsWithNameCompleteResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPatientsWithNameComplete", ReplyAction="*")]
        WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponse GetAllPatientsWithNameComplete(WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllPatientsWithNameComplete", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponse> GetAllPatientsWithNameCompleteAsync(WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento patient del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePatient", ReplyAction="*")]
        WSClient.ServicePatient.UpdatePatientResponse UpdatePatient(WSClient.ServicePatient.UpdatePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdatePatient", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServicePatient.UpdatePatientResponse> UpdatePatientAsync(WSClient.ServicePatient.UpdatePatientRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePatient", ReplyAction="*")]
        bool DeletePatient(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeletePatient", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeletePatientAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento searchByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchById", ReplyAction="*")]
        WSClient.ServicePatient.searchByIdResponse searchById(WSClient.ServicePatient.searchByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/searchById", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServicePatient.searchByIdResponse> searchByIdAsync(WSClient.ServicePatient.searchByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePatient", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.CreatePatientRequestBody Body;
        
        public CreatePatientRequest() {
        }
        
        public CreatePatientRequest(WSClient.ServicePatient.CreatePatientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePatientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServicePatient.VO_Patient patient;
        
        public CreatePatientRequestBody() {
        }
        
        public CreatePatientRequestBody(WSClient.ServicePatient.VO_Patient patient) {
            this.patient = patient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreatePatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreatePatientResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.CreatePatientResponseBody Body;
        
        public CreatePatientResponse() {
        }
        
        public CreatePatientResponse(WSClient.ServicePatient.CreatePatientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreatePatientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreatePatientResult;
        
        public CreatePatientResponseBody() {
        }
        
        public CreatePatientResponseBody(int CreatePatientResult) {
            this.CreatePatientResult = CreatePatientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPatientsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPatients", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.GetAllPatientsRequestBody Body;
        
        public GetAllPatientsRequest() {
        }
        
        public GetAllPatientsRequest(WSClient.ServicePatient.GetAllPatientsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPatientsRequestBody {
        
        public GetAllPatientsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPatientsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPatientsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.GetAllPatientsResponseBody Body;
        
        public GetAllPatientsResponse() {
        }
        
        public GetAllPatientsResponse(WSClient.ServicePatient.GetAllPatientsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPatientsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServicePatient.VO_Patient[] GetAllPatientsResult;
        
        public GetAllPatientsResponseBody() {
        }
        
        public GetAllPatientsResponseBody(WSClient.ServicePatient.VO_Patient[] GetAllPatientsResult) {
            this.GetAllPatientsResult = GetAllPatientsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPatientsWithNameCompleteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPatientsWithNameComplete", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequestBody Body;
        
        public GetAllPatientsWithNameCompleteRequest() {
        }
        
        public GetAllPatientsWithNameCompleteRequest(WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllPatientsWithNameCompleteRequestBody {
        
        public GetAllPatientsWithNameCompleteRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllPatientsWithNameCompleteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllPatientsWithNameCompleteResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponseBody Body;
        
        public GetAllPatientsWithNameCompleteResponse() {
        }
        
        public GetAllPatientsWithNameCompleteResponse(WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllPatientsWithNameCompleteResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServicePatient.VO_Patient[] GetAllPatientsWithNameCompleteResult;
        
        public GetAllPatientsWithNameCompleteResponseBody() {
        }
        
        public GetAllPatientsWithNameCompleteResponseBody(WSClient.ServicePatient.VO_Patient[] GetAllPatientsWithNameCompleteResult) {
            this.GetAllPatientsWithNameCompleteResult = GetAllPatientsWithNameCompleteResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePatientRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePatient", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.UpdatePatientRequestBody Body;
        
        public UpdatePatientRequest() {
        }
        
        public UpdatePatientRequest(WSClient.ServicePatient.UpdatePatientRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePatientRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServicePatient.VO_Patient patient;
        
        public UpdatePatientRequestBody() {
        }
        
        public UpdatePatientRequestBody(WSClient.ServicePatient.VO_Patient patient) {
            this.patient = patient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdatePatientResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdatePatientResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.UpdatePatientResponseBody Body;
        
        public UpdatePatientResponse() {
        }
        
        public UpdatePatientResponse(WSClient.ServicePatient.UpdatePatientResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdatePatientResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdatePatientResult;
        
        public UpdatePatientResponseBody() {
        }
        
        public UpdatePatientResponseBody(bool UpdatePatientResult) {
            this.UpdatePatientResult = UpdatePatientResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchById", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.searchByIdRequestBody Body;
        
        public searchByIdRequest() {
        }
        
        public searchByIdRequest(WSClient.ServicePatient.searchByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idPatient;
        
        public searchByIdRequestBody() {
        }
        
        public searchByIdRequestBody(int idPatient) {
            this.idPatient = idPatient;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class searchByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="searchByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServicePatient.searchByIdResponseBody Body;
        
        public searchByIdResponse() {
        }
        
        public searchByIdResponse(WSClient.ServicePatient.searchByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class searchByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServicePatient.VO_Patient searchByIdResult;
        
        public searchByIdResponseBody() {
        }
        
        public searchByIdResponseBody(WSClient.ServicePatient.VO_Patient searchByIdResult) {
            this.searchByIdResult = searchByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface PatientServiceSoapChannel : WSClient.ServicePatient.PatientServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class PatientServiceSoapClient : System.ServiceModel.ClientBase<WSClient.ServicePatient.PatientServiceSoap>, WSClient.ServicePatient.PatientServiceSoap {
        
        public PatientServiceSoapClient() {
        }
        
        public PatientServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public PatientServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public PatientServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServicePatient.CreatePatientResponse WSClient.ServicePatient.PatientServiceSoap.CreatePatient(WSClient.ServicePatient.CreatePatientRequest request) {
            return base.Channel.CreatePatient(request);
        }
        
        public int CreatePatient(WSClient.ServicePatient.VO_Patient patient) {
            WSClient.ServicePatient.CreatePatientRequest inValue = new WSClient.ServicePatient.CreatePatientRequest();
            inValue.Body = new WSClient.ServicePatient.CreatePatientRequestBody();
            inValue.Body.patient = patient;
            WSClient.ServicePatient.CreatePatientResponse retVal = ((WSClient.ServicePatient.PatientServiceSoap)(this)).CreatePatient(inValue);
            return retVal.Body.CreatePatientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServicePatient.CreatePatientResponse> WSClient.ServicePatient.PatientServiceSoap.CreatePatientAsync(WSClient.ServicePatient.CreatePatientRequest request) {
            return base.Channel.CreatePatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServicePatient.CreatePatientResponse> CreatePatientAsync(WSClient.ServicePatient.VO_Patient patient) {
            WSClient.ServicePatient.CreatePatientRequest inValue = new WSClient.ServicePatient.CreatePatientRequest();
            inValue.Body = new WSClient.ServicePatient.CreatePatientRequestBody();
            inValue.Body.patient = patient;
            return ((WSClient.ServicePatient.PatientServiceSoap)(this)).CreatePatientAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServicePatient.GetAllPatientsResponse WSClient.ServicePatient.PatientServiceSoap.GetAllPatients(WSClient.ServicePatient.GetAllPatientsRequest request) {
            return base.Channel.GetAllPatients(request);
        }
        
        public WSClient.ServicePatient.VO_Patient[] GetAllPatients() {
            WSClient.ServicePatient.GetAllPatientsRequest inValue = new WSClient.ServicePatient.GetAllPatientsRequest();
            inValue.Body = new WSClient.ServicePatient.GetAllPatientsRequestBody();
            WSClient.ServicePatient.GetAllPatientsResponse retVal = ((WSClient.ServicePatient.PatientServiceSoap)(this)).GetAllPatients(inValue);
            return retVal.Body.GetAllPatientsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServicePatient.GetAllPatientsResponse> WSClient.ServicePatient.PatientServiceSoap.GetAllPatientsAsync(WSClient.ServicePatient.GetAllPatientsRequest request) {
            return base.Channel.GetAllPatientsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServicePatient.GetAllPatientsResponse> GetAllPatientsAsync() {
            WSClient.ServicePatient.GetAllPatientsRequest inValue = new WSClient.ServicePatient.GetAllPatientsRequest();
            inValue.Body = new WSClient.ServicePatient.GetAllPatientsRequestBody();
            return ((WSClient.ServicePatient.PatientServiceSoap)(this)).GetAllPatientsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponse WSClient.ServicePatient.PatientServiceSoap.GetAllPatientsWithNameComplete(WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest request) {
            return base.Channel.GetAllPatientsWithNameComplete(request);
        }
        
        public WSClient.ServicePatient.VO_Patient[] GetAllPatientsWithNameComplete() {
            WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest inValue = new WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest();
            inValue.Body = new WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequestBody();
            WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponse retVal = ((WSClient.ServicePatient.PatientServiceSoap)(this)).GetAllPatientsWithNameComplete(inValue);
            return retVal.Body.GetAllPatientsWithNameCompleteResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponse> WSClient.ServicePatient.PatientServiceSoap.GetAllPatientsWithNameCompleteAsync(WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest request) {
            return base.Channel.GetAllPatientsWithNameCompleteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServicePatient.GetAllPatientsWithNameCompleteResponse> GetAllPatientsWithNameCompleteAsync() {
            WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest inValue = new WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequest();
            inValue.Body = new WSClient.ServicePatient.GetAllPatientsWithNameCompleteRequestBody();
            return ((WSClient.ServicePatient.PatientServiceSoap)(this)).GetAllPatientsWithNameCompleteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServicePatient.UpdatePatientResponse WSClient.ServicePatient.PatientServiceSoap.UpdatePatient(WSClient.ServicePatient.UpdatePatientRequest request) {
            return base.Channel.UpdatePatient(request);
        }
        
        public bool UpdatePatient(WSClient.ServicePatient.VO_Patient patient) {
            WSClient.ServicePatient.UpdatePatientRequest inValue = new WSClient.ServicePatient.UpdatePatientRequest();
            inValue.Body = new WSClient.ServicePatient.UpdatePatientRequestBody();
            inValue.Body.patient = patient;
            WSClient.ServicePatient.UpdatePatientResponse retVal = ((WSClient.ServicePatient.PatientServiceSoap)(this)).UpdatePatient(inValue);
            return retVal.Body.UpdatePatientResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServicePatient.UpdatePatientResponse> WSClient.ServicePatient.PatientServiceSoap.UpdatePatientAsync(WSClient.ServicePatient.UpdatePatientRequest request) {
            return base.Channel.UpdatePatientAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServicePatient.UpdatePatientResponse> UpdatePatientAsync(WSClient.ServicePatient.VO_Patient patient) {
            WSClient.ServicePatient.UpdatePatientRequest inValue = new WSClient.ServicePatient.UpdatePatientRequest();
            inValue.Body = new WSClient.ServicePatient.UpdatePatientRequestBody();
            inValue.Body.patient = patient;
            return ((WSClient.ServicePatient.PatientServiceSoap)(this)).UpdatePatientAsync(inValue);
        }
        
        public bool DeletePatient(int id) {
            return base.Channel.DeletePatient(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeletePatientAsync(int id) {
            return base.Channel.DeletePatientAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServicePatient.searchByIdResponse WSClient.ServicePatient.PatientServiceSoap.searchById(WSClient.ServicePatient.searchByIdRequest request) {
            return base.Channel.searchById(request);
        }
        
        public WSClient.ServicePatient.VO_Patient searchById(int idPatient) {
            WSClient.ServicePatient.searchByIdRequest inValue = new WSClient.ServicePatient.searchByIdRequest();
            inValue.Body = new WSClient.ServicePatient.searchByIdRequestBody();
            inValue.Body.idPatient = idPatient;
            WSClient.ServicePatient.searchByIdResponse retVal = ((WSClient.ServicePatient.PatientServiceSoap)(this)).searchById(inValue);
            return retVal.Body.searchByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServicePatient.searchByIdResponse> WSClient.ServicePatient.PatientServiceSoap.searchByIdAsync(WSClient.ServicePatient.searchByIdRequest request) {
            return base.Channel.searchByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServicePatient.searchByIdResponse> searchByIdAsync(int idPatient) {
            WSClient.ServicePatient.searchByIdRequest inValue = new WSClient.ServicePatient.searchByIdRequest();
            inValue.Body = new WSClient.ServicePatient.searchByIdRequestBody();
            inValue.Body.idPatient = idPatient;
            return ((WSClient.ServicePatient.PatientServiceSoap)(this)).searchByIdAsync(inValue);
        }
    }
}
