//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServiceTreatment {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Treatment", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Treatment : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string RecommendTreatmentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string StartedDateField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private WSClient.ServiceTreatment.VO_Medicament MedicamentField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdTreatment {
            get {
                return this.IdTreatmentField;
            }
            set {
                if ((this.IdTreatmentField.Equals(value) != true)) {
                    this.IdTreatmentField = value;
                    this.RaisePropertyChanged("IdTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string RecommendTreatment {
            get {
                return this.RecommendTreatmentField;
            }
            set {
                if ((object.ReferenceEquals(this.RecommendTreatmentField, value) != true)) {
                    this.RecommendTreatmentField = value;
                    this.RaisePropertyChanged("RecommendTreatment");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string StartedDate {
            get {
                return this.StartedDateField;
            }
            set {
                if ((object.ReferenceEquals(this.StartedDateField, value) != true)) {
                    this.StartedDateField = value;
                    this.RaisePropertyChanged("StartedDate");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public WSClient.ServiceTreatment.VO_Medicament Medicament {
            get {
                return this.MedicamentField;
            }
            set {
                if ((object.ReferenceEquals(this.MedicamentField, value) != true)) {
                    this.MedicamentField = value;
                    this.RaisePropertyChanged("Medicament");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Medicament", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Medicament : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdMedicamentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NameMedicamentField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DoseField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string UseInstructionField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdMedicament {
            get {
                return this.IdMedicamentField;
            }
            set {
                if ((this.IdMedicamentField.Equals(value) != true)) {
                    this.IdMedicamentField = value;
                    this.RaisePropertyChanged("IdMedicament");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NameMedicament {
            get {
                return this.NameMedicamentField;
            }
            set {
                if ((object.ReferenceEquals(this.NameMedicamentField, value) != true)) {
                    this.NameMedicamentField = value;
                    this.RaisePropertyChanged("NameMedicament");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string Dose {
            get {
                return this.DoseField;
            }
            set {
                if ((object.ReferenceEquals(this.DoseField, value) != true)) {
                    this.DoseField = value;
                    this.RaisePropertyChanged("Dose");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string UseInstruction {
            get {
                return this.UseInstructionField;
            }
            set {
                if ((object.ReferenceEquals(this.UseInstructionField, value) != true)) {
                    this.UseInstructionField = value;
                    this.RaisePropertyChanged("UseInstruction");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceTreatment.TreatmentServiceSoap")]
    public interface TreatmentServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento treatment del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTreatment", ReplyAction="*")]
        WSClient.ServiceTreatment.CreateTreatmentResponse CreateTreatment(WSClient.ServiceTreatment.CreateTreatmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateTreatment", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.CreateTreatmentResponse> CreateTreatmentAsync(WSClient.ServiceTreatment.CreateTreatmentRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetAllTreatmentsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTreatments", ReplyAction="*")]
        WSClient.ServiceTreatment.GetAllTreatmentsResponse GetAllTreatments(WSClient.ServiceTreatment.GetAllTreatmentsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetAllTreatments", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetAllTreatmentsResponse> GetAllTreatmentsAsync(WSClient.ServiceTreatment.GetAllTreatmentsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento treatment del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTreatment", ReplyAction="*")]
        WSClient.ServiceTreatment.UpdateTreatmentResponse UpdateTreatment(WSClient.ServiceTreatment.UpdateTreatmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateTreatment", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.UpdateTreatmentResponse> UpdateTreatmentAsync(WSClient.ServiceTreatment.UpdateTreatmentRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTreatment", ReplyAction="*")]
        bool DeleteTreatment(int id);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteTreatment", ReplyAction="*")]
        System.Threading.Tasks.Task<bool> DeleteTreatmentAsync(int id);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetTreatmentByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTreatmentById", ReplyAction="*")]
        WSClient.ServiceTreatment.GetTreatmentByIdResponse GetTreatmentById(WSClient.ServiceTreatment.GetTreatmentByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTreatmentById", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetTreatmentByIdResponse> GetTreatmentByIdAsync(WSClient.ServiceTreatment.GetTreatmentByIdRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetTreatmentByMedicamentIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTreatmentByMedicamentId", ReplyAction="*")]
        WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponse GetTreatmentByMedicamentId(WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetTreatmentByMedicamentId", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponse> GetTreatmentByMedicamentIdAsync(WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTreatmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTreatment", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.CreateTreatmentRequestBody Body;
        
        public CreateTreatmentRequest() {
        }
        
        public CreateTreatmentRequest(WSClient.ServiceTreatment.CreateTreatmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTreatmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceTreatment.VO_Treatment treatment;
        
        public CreateTreatmentRequestBody() {
        }
        
        public CreateTreatmentRequestBody(WSClient.ServiceTreatment.VO_Treatment treatment) {
            this.treatment = treatment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateTreatmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateTreatmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.CreateTreatmentResponseBody Body;
        
        public CreateTreatmentResponse() {
        }
        
        public CreateTreatmentResponse(WSClient.ServiceTreatment.CreateTreatmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateTreatmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int CreateTreatmentResult;
        
        public CreateTreatmentResponseBody() {
        }
        
        public CreateTreatmentResponseBody(int CreateTreatmentResult) {
            this.CreateTreatmentResult = CreateTreatmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTreatmentsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTreatments", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.GetAllTreatmentsRequestBody Body;
        
        public GetAllTreatmentsRequest() {
        }
        
        public GetAllTreatmentsRequest(WSClient.ServiceTreatment.GetAllTreatmentsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetAllTreatmentsRequestBody {
        
        public GetAllTreatmentsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetAllTreatmentsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetAllTreatmentsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.GetAllTreatmentsResponseBody Body;
        
        public GetAllTreatmentsResponse() {
        }
        
        public GetAllTreatmentsResponse(WSClient.ServiceTreatment.GetAllTreatmentsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetAllTreatmentsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceTreatment.VO_Treatment[] GetAllTreatmentsResult;
        
        public GetAllTreatmentsResponseBody() {
        }
        
        public GetAllTreatmentsResponseBody(WSClient.ServiceTreatment.VO_Treatment[] GetAllTreatmentsResult) {
            this.GetAllTreatmentsResult = GetAllTreatmentsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTreatmentRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTreatment", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.UpdateTreatmentRequestBody Body;
        
        public UpdateTreatmentRequest() {
        }
        
        public UpdateTreatmentRequest(WSClient.ServiceTreatment.UpdateTreatmentRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTreatmentRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceTreatment.VO_Treatment treatment;
        
        public UpdateTreatmentRequestBody() {
        }
        
        public UpdateTreatmentRequestBody(WSClient.ServiceTreatment.VO_Treatment treatment) {
            this.treatment = treatment;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateTreatmentResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateTreatmentResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.UpdateTreatmentResponseBody Body;
        
        public UpdateTreatmentResponse() {
        }
        
        public UpdateTreatmentResponse(WSClient.ServiceTreatment.UpdateTreatmentResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateTreatmentResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public bool UpdateTreatmentResult;
        
        public UpdateTreatmentResponseBody() {
        }
        
        public UpdateTreatmentResponseBody(bool UpdateTreatmentResult) {
            this.UpdateTreatmentResult = UpdateTreatmentResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTreatmentByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTreatmentById", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.GetTreatmentByIdRequestBody Body;
        
        public GetTreatmentByIdRequest() {
        }
        
        public GetTreatmentByIdRequest(WSClient.ServiceTreatment.GetTreatmentByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTreatmentByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetTreatmentByIdRequestBody() {
        }
        
        public GetTreatmentByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTreatmentByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTreatmentByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.GetTreatmentByIdResponseBody Body;
        
        public GetTreatmentByIdResponse() {
        }
        
        public GetTreatmentByIdResponse(WSClient.ServiceTreatment.GetTreatmentByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTreatmentByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceTreatment.VO_Treatment GetTreatmentByIdResult;
        
        public GetTreatmentByIdResponseBody() {
        }
        
        public GetTreatmentByIdResponseBody(WSClient.ServiceTreatment.VO_Treatment GetTreatmentByIdResult) {
            this.GetTreatmentByIdResult = GetTreatmentByIdResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTreatmentByMedicamentIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTreatmentByMedicamentId", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequestBody Body;
        
        public GetTreatmentByMedicamentIdRequest() {
        }
        
        public GetTreatmentByMedicamentIdRequest(WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTreatmentByMedicamentIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idMedicament;
        
        public GetTreatmentByMedicamentIdRequestBody() {
        }
        
        public GetTreatmentByMedicamentIdRequestBody(int idMedicament) {
            this.idMedicament = idMedicament;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetTreatmentByMedicamentIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetTreatmentByMedicamentIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponseBody Body;
        
        public GetTreatmentByMedicamentIdResponse() {
        }
        
        public GetTreatmentByMedicamentIdResponse(WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetTreatmentByMedicamentIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceTreatment.VO_Treatment GetTreatmentByMedicamentIdResult;
        
        public GetTreatmentByMedicamentIdResponseBody() {
        }
        
        public GetTreatmentByMedicamentIdResponseBody(WSClient.ServiceTreatment.VO_Treatment GetTreatmentByMedicamentIdResult) {
            this.GetTreatmentByMedicamentIdResult = GetTreatmentByMedicamentIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TreatmentServiceSoapChannel : WSClient.ServiceTreatment.TreatmentServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TreatmentServiceSoapClient : System.ServiceModel.ClientBase<WSClient.ServiceTreatment.TreatmentServiceSoap>, WSClient.ServiceTreatment.TreatmentServiceSoap {
        
        public TreatmentServiceSoapClient() {
        }
        
        public TreatmentServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TreatmentServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreatmentServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TreatmentServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceTreatment.CreateTreatmentResponse WSClient.ServiceTreatment.TreatmentServiceSoap.CreateTreatment(WSClient.ServiceTreatment.CreateTreatmentRequest request) {
            return base.Channel.CreateTreatment(request);
        }
        
        public int CreateTreatment(WSClient.ServiceTreatment.VO_Treatment treatment) {
            WSClient.ServiceTreatment.CreateTreatmentRequest inValue = new WSClient.ServiceTreatment.CreateTreatmentRequest();
            inValue.Body = new WSClient.ServiceTreatment.CreateTreatmentRequestBody();
            inValue.Body.treatment = treatment;
            WSClient.ServiceTreatment.CreateTreatmentResponse retVal = ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).CreateTreatment(inValue);
            return retVal.Body.CreateTreatmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.CreateTreatmentResponse> WSClient.ServiceTreatment.TreatmentServiceSoap.CreateTreatmentAsync(WSClient.ServiceTreatment.CreateTreatmentRequest request) {
            return base.Channel.CreateTreatmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceTreatment.CreateTreatmentResponse> CreateTreatmentAsync(WSClient.ServiceTreatment.VO_Treatment treatment) {
            WSClient.ServiceTreatment.CreateTreatmentRequest inValue = new WSClient.ServiceTreatment.CreateTreatmentRequest();
            inValue.Body = new WSClient.ServiceTreatment.CreateTreatmentRequestBody();
            inValue.Body.treatment = treatment;
            return ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).CreateTreatmentAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceTreatment.GetAllTreatmentsResponse WSClient.ServiceTreatment.TreatmentServiceSoap.GetAllTreatments(WSClient.ServiceTreatment.GetAllTreatmentsRequest request) {
            return base.Channel.GetAllTreatments(request);
        }
        
        public WSClient.ServiceTreatment.VO_Treatment[] GetAllTreatments() {
            WSClient.ServiceTreatment.GetAllTreatmentsRequest inValue = new WSClient.ServiceTreatment.GetAllTreatmentsRequest();
            inValue.Body = new WSClient.ServiceTreatment.GetAllTreatmentsRequestBody();
            WSClient.ServiceTreatment.GetAllTreatmentsResponse retVal = ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).GetAllTreatments(inValue);
            return retVal.Body.GetAllTreatmentsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetAllTreatmentsResponse> WSClient.ServiceTreatment.TreatmentServiceSoap.GetAllTreatmentsAsync(WSClient.ServiceTreatment.GetAllTreatmentsRequest request) {
            return base.Channel.GetAllTreatmentsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetAllTreatmentsResponse> GetAllTreatmentsAsync() {
            WSClient.ServiceTreatment.GetAllTreatmentsRequest inValue = new WSClient.ServiceTreatment.GetAllTreatmentsRequest();
            inValue.Body = new WSClient.ServiceTreatment.GetAllTreatmentsRequestBody();
            return ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).GetAllTreatmentsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceTreatment.UpdateTreatmentResponse WSClient.ServiceTreatment.TreatmentServiceSoap.UpdateTreatment(WSClient.ServiceTreatment.UpdateTreatmentRequest request) {
            return base.Channel.UpdateTreatment(request);
        }
        
        public bool UpdateTreatment(WSClient.ServiceTreatment.VO_Treatment treatment) {
            WSClient.ServiceTreatment.UpdateTreatmentRequest inValue = new WSClient.ServiceTreatment.UpdateTreatmentRequest();
            inValue.Body = new WSClient.ServiceTreatment.UpdateTreatmentRequestBody();
            inValue.Body.treatment = treatment;
            WSClient.ServiceTreatment.UpdateTreatmentResponse retVal = ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).UpdateTreatment(inValue);
            return retVal.Body.UpdateTreatmentResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.UpdateTreatmentResponse> WSClient.ServiceTreatment.TreatmentServiceSoap.UpdateTreatmentAsync(WSClient.ServiceTreatment.UpdateTreatmentRequest request) {
            return base.Channel.UpdateTreatmentAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceTreatment.UpdateTreatmentResponse> UpdateTreatmentAsync(WSClient.ServiceTreatment.VO_Treatment treatment) {
            WSClient.ServiceTreatment.UpdateTreatmentRequest inValue = new WSClient.ServiceTreatment.UpdateTreatmentRequest();
            inValue.Body = new WSClient.ServiceTreatment.UpdateTreatmentRequestBody();
            inValue.Body.treatment = treatment;
            return ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).UpdateTreatmentAsync(inValue);
        }
        
        public bool DeleteTreatment(int id) {
            return base.Channel.DeleteTreatment(id);
        }
        
        public System.Threading.Tasks.Task<bool> DeleteTreatmentAsync(int id) {
            return base.Channel.DeleteTreatmentAsync(id);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceTreatment.GetTreatmentByIdResponse WSClient.ServiceTreatment.TreatmentServiceSoap.GetTreatmentById(WSClient.ServiceTreatment.GetTreatmentByIdRequest request) {
            return base.Channel.GetTreatmentById(request);
        }
        
        public WSClient.ServiceTreatment.VO_Treatment GetTreatmentById(int id) {
            WSClient.ServiceTreatment.GetTreatmentByIdRequest inValue = new WSClient.ServiceTreatment.GetTreatmentByIdRequest();
            inValue.Body = new WSClient.ServiceTreatment.GetTreatmentByIdRequestBody();
            inValue.Body.id = id;
            WSClient.ServiceTreatment.GetTreatmentByIdResponse retVal = ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).GetTreatmentById(inValue);
            return retVal.Body.GetTreatmentByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetTreatmentByIdResponse> WSClient.ServiceTreatment.TreatmentServiceSoap.GetTreatmentByIdAsync(WSClient.ServiceTreatment.GetTreatmentByIdRequest request) {
            return base.Channel.GetTreatmentByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetTreatmentByIdResponse> GetTreatmentByIdAsync(int id) {
            WSClient.ServiceTreatment.GetTreatmentByIdRequest inValue = new WSClient.ServiceTreatment.GetTreatmentByIdRequest();
            inValue.Body = new WSClient.ServiceTreatment.GetTreatmentByIdRequestBody();
            inValue.Body.id = id;
            return ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).GetTreatmentByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponse WSClient.ServiceTreatment.TreatmentServiceSoap.GetTreatmentByMedicamentId(WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest request) {
            return base.Channel.GetTreatmentByMedicamentId(request);
        }
        
        public WSClient.ServiceTreatment.VO_Treatment GetTreatmentByMedicamentId(int idMedicament) {
            WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest inValue = new WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest();
            inValue.Body = new WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequestBody();
            inValue.Body.idMedicament = idMedicament;
            WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponse retVal = ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).GetTreatmentByMedicamentId(inValue);
            return retVal.Body.GetTreatmentByMedicamentIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponse> WSClient.ServiceTreatment.TreatmentServiceSoap.GetTreatmentByMedicamentIdAsync(WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest request) {
            return base.Channel.GetTreatmentByMedicamentIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceTreatment.GetTreatmentByMedicamentIdResponse> GetTreatmentByMedicamentIdAsync(int idMedicament) {
            WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest inValue = new WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequest();
            inValue.Body = new WSClient.ServiceTreatment.GetTreatmentByMedicamentIdRequestBody();
            inValue.Body.idMedicament = idMedicament;
            return ((WSClient.ServiceTreatment.TreatmentServiceSoap)(this)).GetTreatmentByMedicamentIdAsync(inValue);
        }
    }
}
