//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WSClient.ServiceLabResult {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="VO_Laboratory_Result", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class VO_Laboratory_Result : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdLaboratoryResultField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string TestField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string ResultValueField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string DateDoneField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int IdLaboratoryResult {
            get {
                return this.IdLaboratoryResultField;
            }
            set {
                if ((this.IdLaboratoryResultField.Equals(value) != true)) {
                    this.IdLaboratoryResultField = value;
                    this.RaisePropertyChanged("IdLaboratoryResult");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Test {
            get {
                return this.TestField;
            }
            set {
                if ((object.ReferenceEquals(this.TestField, value) != true)) {
                    this.TestField = value;
                    this.RaisePropertyChanged("Test");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=2)]
        public string ResultValue {
            get {
                return this.ResultValueField;
            }
            set {
                if ((object.ReferenceEquals(this.ResultValueField, value) != true)) {
                    this.ResultValueField = value;
                    this.RaisePropertyChanged("ResultValue");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=3)]
        public string DateDone {
            get {
                return this.DateDoneField;
            }
            set {
                if ((object.ReferenceEquals(this.DateDoneField, value) != true)) {
                    this.DateDoneField = value;
                    this.RaisePropertyChanged("DateDone");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServiceLabResult.LabResultServiceSoap")]
    public interface LabResultServiceSoap {
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento lr del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateLabResult", ReplyAction="*")]
        WSClient.ServiceLabResult.CreateLabResultResponse CreateLabResult(WSClient.ServiceLabResult.CreateLabResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/CreateLabResult", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.CreateLabResultResponse> CreateLabResultAsync(WSClient.ServiceLabResult.CreateLabResultRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento ListLabResultsResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListLabResults", ReplyAction="*")]
        WSClient.ServiceLabResult.ListLabResultsResponse ListLabResults(WSClient.ServiceLabResult.ListLabResultsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/ListLabResults", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.ListLabResultsResponse> ListLabResultsAsync(WSClient.ServiceLabResult.ListLabResultsRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento lr del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLabResult", ReplyAction="*")]
        WSClient.ServiceLabResult.UpdateLabResultResponse UpdateLabResult(WSClient.ServiceLabResult.UpdateLabResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/UpdateLabResult", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.UpdateLabResultResponse> UpdateLabResultAsync(WSClient.ServiceLabResult.UpdateLabResultRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento DeleteLabResultResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLabResult", ReplyAction="*")]
        WSClient.ServiceLabResult.DeleteLabResultResponse DeleteLabResult(WSClient.ServiceLabResult.DeleteLabResultRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/DeleteLabResult", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.DeleteLabResultResponse> DeleteLabResultAsync(WSClient.ServiceLabResult.DeleteLabResultRequest request);
        
        // CODEGEN: Se está generando un contrato de mensaje, ya que el nombre de elemento GetLaboratoryResultByIdResult del espacio de nombres http://tempuri.org/ no está marcado para aceptar valores nil.
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLaboratoryResultById", ReplyAction="*")]
        WSClient.ServiceLabResult.GetLaboratoryResultByIdResponse GetLaboratoryResultById(WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetLaboratoryResultById", ReplyAction="*")]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.GetLaboratoryResultByIdResponse> GetLaboratoryResultByIdAsync(WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLabResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLabResult", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.CreateLabResultRequestBody Body;
        
        public CreateLabResultRequest() {
        }
        
        public CreateLabResultRequest(WSClient.ServiceLabResult.CreateLabResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateLabResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceLabResult.VO_Laboratory_Result lr;
        
        public CreateLabResultRequestBody() {
        }
        
        public CreateLabResultRequestBody(WSClient.ServiceLabResult.VO_Laboratory_Result lr) {
            this.lr = lr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class CreateLabResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="CreateLabResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.CreateLabResultResponseBody Body;
        
        public CreateLabResultResponse() {
        }
        
        public CreateLabResultResponse(WSClient.ServiceLabResult.CreateLabResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class CreateLabResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string CreateLabResultResult;
        
        public CreateLabResultResponseBody() {
        }
        
        public CreateLabResultResponseBody(string CreateLabResultResult) {
            this.CreateLabResultResult = CreateLabResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListLabResultsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListLabResults", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.ListLabResultsRequestBody Body;
        
        public ListLabResultsRequest() {
        }
        
        public ListLabResultsRequest(WSClient.ServiceLabResult.ListLabResultsRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class ListLabResultsRequestBody {
        
        public ListLabResultsRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class ListLabResultsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="ListLabResultsResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.ListLabResultsResponseBody Body;
        
        public ListLabResultsResponse() {
        }
        
        public ListLabResultsResponse(WSClient.ServiceLabResult.ListLabResultsResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class ListLabResultsResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceLabResult.VO_Laboratory_Result[] ListLabResultsResult;
        
        public ListLabResultsResponseBody() {
        }
        
        public ListLabResultsResponseBody(WSClient.ServiceLabResult.VO_Laboratory_Result[] ListLabResultsResult) {
            this.ListLabResultsResult = ListLabResultsResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLabResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLabResult", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.UpdateLabResultRequestBody Body;
        
        public UpdateLabResultRequest() {
        }
        
        public UpdateLabResultRequest(WSClient.ServiceLabResult.UpdateLabResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLabResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceLabResult.VO_Laboratory_Result lr;
        
        public UpdateLabResultRequestBody() {
        }
        
        public UpdateLabResultRequestBody(WSClient.ServiceLabResult.VO_Laboratory_Result lr) {
            this.lr = lr;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class UpdateLabResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="UpdateLabResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.UpdateLabResultResponseBody Body;
        
        public UpdateLabResultResponse() {
        }
        
        public UpdateLabResultResponse(WSClient.ServiceLabResult.UpdateLabResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class UpdateLabResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string UpdateLabResultResult;
        
        public UpdateLabResultResponseBody() {
        }
        
        public UpdateLabResultResponseBody(string UpdateLabResultResult) {
            this.UpdateLabResultResult = UpdateLabResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLabResultRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLabResult", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.DeleteLabResultRequestBody Body;
        
        public DeleteLabResultRequest() {
        }
        
        public DeleteLabResultRequest(WSClient.ServiceLabResult.DeleteLabResultRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteLabResultRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int idLab;
        
        public DeleteLabResultRequestBody() {
        }
        
        public DeleteLabResultRequestBody(int idLab) {
            this.idLab = idLab;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class DeleteLabResultResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="DeleteLabResultResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.DeleteLabResultResponseBody Body;
        
        public DeleteLabResultResponse() {
        }
        
        public DeleteLabResultResponse(WSClient.ServiceLabResult.DeleteLabResultResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class DeleteLabResultResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string DeleteLabResultResult;
        
        public DeleteLabResultResponseBody() {
        }
        
        public DeleteLabResultResponseBody(string DeleteLabResultResult) {
            this.DeleteLabResultResult = DeleteLabResultResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLaboratoryResultByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLaboratoryResultById", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.GetLaboratoryResultByIdRequestBody Body;
        
        public GetLaboratoryResultByIdRequest() {
        }
        
        public GetLaboratoryResultByIdRequest(WSClient.ServiceLabResult.GetLaboratoryResultByIdRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLaboratoryResultByIdRequestBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(Order=0)]
        public int id;
        
        public GetLaboratoryResultByIdRequestBody() {
        }
        
        public GetLaboratoryResultByIdRequestBody(int id) {
            this.id = id;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetLaboratoryResultByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetLaboratoryResultByIdResponse", Namespace="http://tempuri.org/", Order=0)]
        public WSClient.ServiceLabResult.GetLaboratoryResultByIdResponseBody Body;
        
        public GetLaboratoryResultByIdResponse() {
        }
        
        public GetLaboratoryResultByIdResponse(WSClient.ServiceLabResult.GetLaboratoryResultByIdResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetLaboratoryResultByIdResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public WSClient.ServiceLabResult.VO_Laboratory_Result GetLaboratoryResultByIdResult;
        
        public GetLaboratoryResultByIdResponseBody() {
        }
        
        public GetLaboratoryResultByIdResponseBody(WSClient.ServiceLabResult.VO_Laboratory_Result GetLaboratoryResultByIdResult) {
            this.GetLaboratoryResultByIdResult = GetLaboratoryResultByIdResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface LabResultServiceSoapChannel : WSClient.ServiceLabResult.LabResultServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class LabResultServiceSoapClient : System.ServiceModel.ClientBase<WSClient.ServiceLabResult.LabResultServiceSoap>, WSClient.ServiceLabResult.LabResultServiceSoap {
        
        public LabResultServiceSoapClient() {
        }
        
        public LabResultServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public LabResultServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabResultServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public LabResultServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceLabResult.CreateLabResultResponse WSClient.ServiceLabResult.LabResultServiceSoap.CreateLabResult(WSClient.ServiceLabResult.CreateLabResultRequest request) {
            return base.Channel.CreateLabResult(request);
        }
        
        public string CreateLabResult(WSClient.ServiceLabResult.VO_Laboratory_Result lr) {
            WSClient.ServiceLabResult.CreateLabResultRequest inValue = new WSClient.ServiceLabResult.CreateLabResultRequest();
            inValue.Body = new WSClient.ServiceLabResult.CreateLabResultRequestBody();
            inValue.Body.lr = lr;
            WSClient.ServiceLabResult.CreateLabResultResponse retVal = ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).CreateLabResult(inValue);
            return retVal.Body.CreateLabResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.CreateLabResultResponse> WSClient.ServiceLabResult.LabResultServiceSoap.CreateLabResultAsync(WSClient.ServiceLabResult.CreateLabResultRequest request) {
            return base.Channel.CreateLabResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceLabResult.CreateLabResultResponse> CreateLabResultAsync(WSClient.ServiceLabResult.VO_Laboratory_Result lr) {
            WSClient.ServiceLabResult.CreateLabResultRequest inValue = new WSClient.ServiceLabResult.CreateLabResultRequest();
            inValue.Body = new WSClient.ServiceLabResult.CreateLabResultRequestBody();
            inValue.Body.lr = lr;
            return ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).CreateLabResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceLabResult.ListLabResultsResponse WSClient.ServiceLabResult.LabResultServiceSoap.ListLabResults(WSClient.ServiceLabResult.ListLabResultsRequest request) {
            return base.Channel.ListLabResults(request);
        }
        
        public WSClient.ServiceLabResult.VO_Laboratory_Result[] ListLabResults() {
            WSClient.ServiceLabResult.ListLabResultsRequest inValue = new WSClient.ServiceLabResult.ListLabResultsRequest();
            inValue.Body = new WSClient.ServiceLabResult.ListLabResultsRequestBody();
            WSClient.ServiceLabResult.ListLabResultsResponse retVal = ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).ListLabResults(inValue);
            return retVal.Body.ListLabResultsResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.ListLabResultsResponse> WSClient.ServiceLabResult.LabResultServiceSoap.ListLabResultsAsync(WSClient.ServiceLabResult.ListLabResultsRequest request) {
            return base.Channel.ListLabResultsAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceLabResult.ListLabResultsResponse> ListLabResultsAsync() {
            WSClient.ServiceLabResult.ListLabResultsRequest inValue = new WSClient.ServiceLabResult.ListLabResultsRequest();
            inValue.Body = new WSClient.ServiceLabResult.ListLabResultsRequestBody();
            return ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).ListLabResultsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceLabResult.UpdateLabResultResponse WSClient.ServiceLabResult.LabResultServiceSoap.UpdateLabResult(WSClient.ServiceLabResult.UpdateLabResultRequest request) {
            return base.Channel.UpdateLabResult(request);
        }
        
        public string UpdateLabResult(WSClient.ServiceLabResult.VO_Laboratory_Result lr) {
            WSClient.ServiceLabResult.UpdateLabResultRequest inValue = new WSClient.ServiceLabResult.UpdateLabResultRequest();
            inValue.Body = new WSClient.ServiceLabResult.UpdateLabResultRequestBody();
            inValue.Body.lr = lr;
            WSClient.ServiceLabResult.UpdateLabResultResponse retVal = ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).UpdateLabResult(inValue);
            return retVal.Body.UpdateLabResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.UpdateLabResultResponse> WSClient.ServiceLabResult.LabResultServiceSoap.UpdateLabResultAsync(WSClient.ServiceLabResult.UpdateLabResultRequest request) {
            return base.Channel.UpdateLabResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceLabResult.UpdateLabResultResponse> UpdateLabResultAsync(WSClient.ServiceLabResult.VO_Laboratory_Result lr) {
            WSClient.ServiceLabResult.UpdateLabResultRequest inValue = new WSClient.ServiceLabResult.UpdateLabResultRequest();
            inValue.Body = new WSClient.ServiceLabResult.UpdateLabResultRequestBody();
            inValue.Body.lr = lr;
            return ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).UpdateLabResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceLabResult.DeleteLabResultResponse WSClient.ServiceLabResult.LabResultServiceSoap.DeleteLabResult(WSClient.ServiceLabResult.DeleteLabResultRequest request) {
            return base.Channel.DeleteLabResult(request);
        }
        
        public string DeleteLabResult(int idLab) {
            WSClient.ServiceLabResult.DeleteLabResultRequest inValue = new WSClient.ServiceLabResult.DeleteLabResultRequest();
            inValue.Body = new WSClient.ServiceLabResult.DeleteLabResultRequestBody();
            inValue.Body.idLab = idLab;
            WSClient.ServiceLabResult.DeleteLabResultResponse retVal = ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).DeleteLabResult(inValue);
            return retVal.Body.DeleteLabResultResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.DeleteLabResultResponse> WSClient.ServiceLabResult.LabResultServiceSoap.DeleteLabResultAsync(WSClient.ServiceLabResult.DeleteLabResultRequest request) {
            return base.Channel.DeleteLabResultAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceLabResult.DeleteLabResultResponse> DeleteLabResultAsync(int idLab) {
            WSClient.ServiceLabResult.DeleteLabResultRequest inValue = new WSClient.ServiceLabResult.DeleteLabResultRequest();
            inValue.Body = new WSClient.ServiceLabResult.DeleteLabResultRequestBody();
            inValue.Body.idLab = idLab;
            return ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).DeleteLabResultAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WSClient.ServiceLabResult.GetLaboratoryResultByIdResponse WSClient.ServiceLabResult.LabResultServiceSoap.GetLaboratoryResultById(WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest request) {
            return base.Channel.GetLaboratoryResultById(request);
        }
        
        public WSClient.ServiceLabResult.VO_Laboratory_Result GetLaboratoryResultById(int id) {
            WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest inValue = new WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest();
            inValue.Body = new WSClient.ServiceLabResult.GetLaboratoryResultByIdRequestBody();
            inValue.Body.id = id;
            WSClient.ServiceLabResult.GetLaboratoryResultByIdResponse retVal = ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).GetLaboratoryResultById(inValue);
            return retVal.Body.GetLaboratoryResultByIdResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WSClient.ServiceLabResult.GetLaboratoryResultByIdResponse> WSClient.ServiceLabResult.LabResultServiceSoap.GetLaboratoryResultByIdAsync(WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest request) {
            return base.Channel.GetLaboratoryResultByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<WSClient.ServiceLabResult.GetLaboratoryResultByIdResponse> GetLaboratoryResultByIdAsync(int id) {
            WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest inValue = new WSClient.ServiceLabResult.GetLaboratoryResultByIdRequest();
            inValue.Body = new WSClient.ServiceLabResult.GetLaboratoryResultByIdRequestBody();
            inValue.Body.id = id;
            return ((WSClient.ServiceLabResult.LabResultServiceSoap)(this)).GetLaboratoryResultByIdAsync(inValue);
        }
    }
}
